#!/bin/bash
# --- alias --- #
function alias-if-exist {
  if command -v $1 >/dev/null;then
    alias_name="${$3:-$1}"
    alias $2="$alias_name"
  fi
}

alias-if-exist exa ls
alias-if-exist batcat bat
alias-if-exist batcat cat 'batcat -p --paging=never'
alias-if-exist proxychains pc 'proxychains -q'

# --- function --- #
proxy_path="$HOME/clash"
function gnome-manual() {
    gsettings set org.gnome.system.proxy mode 'manual' # gnome proxy method manual|auto|none
    gsettings set org.gnome.system.proxy.http host localhost
    gsettings set org.gnome.system.proxy.http port 7890
    gsettings set org.gnome.system.proxy.https host localhost
    gsettings set org.gnome.system.proxy.https port 7890
    gsettings set org.gnome.system.proxy.socks host localhost
    gsettings set org.gnome.system.proxy.socks port 7891

}
# network mode
# manual|auto|none
function start-proxy(){
    gnome-manual
    set-proxy && ${proxy_path}/clash -d ${proxy_path}/ &
    echo "start clash successfully!"
}
function stop-proxy(){
    gsettings set org.gnome.system.proxy mode 'none' # disable
    pgrep clash|xargs kill && echo "stop clash now"
    # kill -9 $var && echo "stop clash successfully!"
    unset-proxy && echo "unset all proxy variables"
}
function restart-proxy(){
    stop-proxy
    start-proxy
}

