alias Docker="sudo docker"
alias Attach="sudo docker attach"
alias Drm="sudo docker rm"
alias Dps="sudo docker ps"
alias Start="sudo docker start"
alias Stop="sudo docker stop"
alias Restart="sudo docker restart"