# get aliases from bash.old
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# import local files
local ZSH_CONF=$HOME/.zsh
source $ZSH_CONF/functions.zsh
source $ZSH_CONF/bindings.zsh
source $ZSH_CONF/history.zsh
source $ZSH_CONF/utility.zsh


eval "$(oh-my-posh init zsh --config ~/.poshthemes/lambda.json)"