# Created by newuser for 5.8
# source /usr/share/powerlevel9k/powerlevel9k.zsh-theme

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# import local files
local ZSH_CONF=$HOME/.zsh
source $ZSH_CONF/functions.zsh
source $ZSH_CONF/bindings.zsh
source $ZSH_CONF/history.zsh
source $ZSH_CONF/utility.zsh
source $ZSH_CONF/tools-alias.zsh


eval "$(oh-my-posh --init --shell zsh --config ~/.poshthemes/lambda.json)"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
source /opt/conda/etc/profile.d/conda.sh

# add go bin to path
export PATH=$HOME/go/bin:$PATH
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
